export const copy = {
  brand: "GYMGO",
  tagline: "Train anywhere. Belong everywhere.",
  hero: "Missed the gym? Not in this city.",
  heroBody: "One hour. The right equipment. A new city that feels like home.",
  searchPlaceholder: "Which city are you training in?",
  explore: "Explore gyms",
  bookings: "My bookings",
  cities: ["BARASAT", "BARRACKPORE", "KOLKATA", "BENGALURU", "LONDON"],
  steps: [
    ["01", "Pick a city", "Search a city, not a postcode."],
    ["02", "Find your fit", "See the gear, vibe and real prices."],
    ["03", "Tap in", "Book a slot and scan your way inside."],
  ],
  empty: "No gyms here yet. Try another city.",
  // A
  bookingTicket: {
    confirmTitle: "Confirm your session",
    dateLabel: "Local date and time",
    demoCheckout: "DEMO CHECKOUT",
    payAtGym: "Pay at gym",
    processing: "Processing demo checkout…",
    confirmBooking: "Confirm booking",
    bookingFailed: "We couldn’t book this hour. Please choose another slot and try again.",
    signInRequired: "Sign in as a traveller to book this session.",
    travellerOnly: "Only traveller accounts can book a gym session.",
    slotFull: "That hour just filled up. Please choose another time.",
    closedHour: "The gym is closed during that hour. Please choose an open slot.",
    inPast: "That hour has already passed. Please choose a future time.",
    tooFarAhead: "Bookings are available up to 7 days ahead. Choose an earlier date.",
    alreadyBooked: "You already have a booking for this gym and hour.",
    priceUnavailable: "This gym has not listed a bookable price yet.",
    sessionBooked: "Your session is booked.",
    ticketTitle: "Your GymGo pass",
    confirmed: "CONFIRMED",
    checkedIn: "Checked in ✓ at",
    qrInstructions: "Show this pass at the gym desk. Your QR is valid from 15 minutes before your session until it ends.",
    cancelBooking: "Cancel booking",
    cancelling: "Cancelling…",
    cancelConfirm: "Cancel this booking?",
    cancelSuccess: "Booking cancelled.",
    cancelTooLate: "Bookings can only be cancelled at least 2 hours before the session.",
    cancelFailed: "We couldn’t cancel this booking. Please try again.",
    bookingNotFound: "Booking not found.",
    liveStatusUnavailable: "Live check-in updates are temporarily unavailable.",
    upcoming: "Upcoming",
    past: "Past",
    noUpcoming: "No upcoming sessions. Find a gym and book your next workout.",
    noPast: "Your completed and cancelled sessions will appear here.",
    ticket: "View pass",
    statusConfirmed: "Confirmed",
    statusCheckedIn: "Checked in",
    statusCancelled: "Cancelled",
  },
  // B
  owner: {
    dashboardEyebrow: "Owner HQ",
    dashboardTitle: "Your floor, your rules.",
    todayBookings: "Today's bookings",
    checkedIn: "Checked in",
    revenueEstimate: "Revenue estimate",
    hourlyTimeline: "Today's floor",
    noGym: "No gym is linked to this owner account yet.",
    noBookings: "No bookings scheduled today.",
    scanEntry: "Scan entry",
    scanDescription: "Validate a member pass.",
    scansLog: "Scans log",
    scansDescription: "Review recent entry attempts.",
    noScans: "No scans recorded yet.",
    scannerEyebrow: "Front desk",
    scannerTitle: "Scan a member pass.",
    cameraUnavailable: "Camera is unavailable. Allow camera access or paste a pass code below.",
    cameraPermission: "Allow camera access, use HTTPS or localhost, or paste the code manually.",
    pasteCode: "Paste QR code",
    submitCode: "Verify pass",
    scanning: "Point the camera at a member QR pass.",
    invalidCode: "Invalid code",
    invalid: "Invalid code. This pass could not be verified.",
    wrongGym: "This pass belongs to a different gym.",
    tooEarly: "This session has not started yet. The pass opens 15 minutes before the slot.",
    expired: "This pass has expired.",
    alreadyUsed: "This pass has already been used.",
    cancelled: "This booking was cancelled.",
    verified: "VERIFIED",
    reasonInvalid: "Invalid code",
    reasonWrongGym: "Wrong gym",
    reasonTooEarly: "Too early",
    reasonExpired: "Expired",
    reasonAlreadyUsed: "Already used",
    reasonCancelled: "Cancelled",
    resultError: "Could not verify this pass. Try again.",
    scanTime: "Scanned at",
    traveller: "Traveller",
    slot: "Session",
    scanResult: "Result",
    scanStatusOk: "Verified",
    scanStatusInvalid: "Invalid",
    scanStatusWrongGym: "Wrong gym",
    scanStatusTooEarly: "Too early",
    scanStatusExpired: "Expired",
    scanStatusReused: "Already used",
    scanStatusCancelled: "Cancelled",
    scanLogTitle: "Recent scans.",
  },
  // C
  liveCity: {
    outsideCoverage: "This area is not covered yet. Load local gyms from the map?",
    loadGyms: "Load gyms here",
    loadingGyms: "Finding gyms nearby…",
    loadingDescription: "We’re checking the city and nearby gym listings.",
    resolveFailed: "Could not identify your city. Please try again.",
    ingestFailed: "Could not load gyms for this area. Please try again later.",
    rateLimited: "Live city search is temporarily limited. Please try again later.",
    locationUnavailable: "Location is not available in this browser.",
    locationPermission: "Location permission was not granted.",
  },
} as const;
